disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - .build
  - Packages

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
    error: 80
